# Generated by Django 5.2.7 on 2026-04-13 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_product_slug_alter_product_image_productimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=250, unique=True),
            preserve_default=False,
        ),
    ]
