# Generated by Django 5.2.7 on 2026-04-13 17:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_product_detailed_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='casestudy',
            name='product',
            field=models.ForeignKey(blank=True, help_text='Link this case study to a dynamic product page', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='case_studies', to='api.product'),
        ),
        migrations.AlterField(
            model_name='casestudy',
            name='link',
            field=models.URLField(blank=True, default='', help_text='External link (fallback if no product linked)'),
        ),
    ]
