# Generated by Django 5.2.7 on 2026-04-14 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_update_product_slugs'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['display_order', 'id']},
        ),
        migrations.AddField(
            model_name='product',
            name='display_order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
