# Generated by Django 5.2.7 on 2026-04-15 11:22

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_product_options_product_display_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='detailed_description',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Long description for the details page', null=True),
        ),
    ]
