"""
Django settings for rocketops_core project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load secrets from rocketops-backend/.env (gitignored). Never hardcode keys.
try:
    from dotenv import load_dotenv
    load_dotenv(BASE_DIR / '.env')
except Exception:
    pass


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-jasxg01g0-)aua+t3p7^w#h$)0pv*xdq@*9_o!z3g4^zc-9(vt'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

# Public URL of the Next.js frontend — used to build "View on site" links in the
# admin (the blog/product pages live on the frontend app, not on this backend).
SITE_URL = os.environ.get(
    'FRONTEND_SITE_URL',
    'http://localhost:3000' if DEBUG else 'https://rocketops.ai',
).rstrip('/')


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework.authtoken',
    'corsheaders',
    'ckeditor',
    'ckeditor_uploader',
    'api',
    'crm',
]

# ── Django REST Framework ─────────────────────────────────────────────────────
# The public marketing/blog endpoints stay open (AllowAny default). The CRM
# endpoints opt into authentication per-view via permission_classes=[IsCRMUser],
# accepting either a DRF token (frontend app) or a session (browsable/admin).
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',
    ],
}

# ── CKEditor (rich text + image upload + tables) ──────────────────────────────
CKEDITOR_UPLOAD_PATH = 'blogs/inline/'
CKEDITOR_IMAGE_BACKEND = 'pillow'
CKEDITOR_RESTRICT_BY_USER = False
CKEDITOR_BROWSE_SHOW_DIRS = True
CKEDITOR_ALLOW_NONIMAGE_FILES = False

CKEDITOR_CONFIGS = {
    # Compact editor kept for existing Product descriptions.
    'default': {
        'toolbar': 'Custom',
        'toolbar_Custom': [
            ['Bold', 'Italic', 'Underline'],
            ['NumberedList', 'BulletedList', '-', 'Outdent', 'Indent', '-', 'JustifyLeft', 'JustifyCenter', 'JustifyRight', 'JustifyBlock'],
            ['Link', 'Unlink'],
            ['RemoveFormat', 'Source']
        ],
        'width': '100%',
    },

    # Full publishing editor for Blog articles — headings, images, tables, code.
    'blog': {
        'toolbar': 'Blog',
        'toolbar_Blog': [
            {'name': 'styles', 'items': ['Format', 'Font', 'FontSize']},
            {'name': 'basic', 'items': ['Bold', 'Italic', 'Underline', 'Strike', 'Subscript', 'Superscript', 'RemoveFormat']},
            {'name': 'colors', 'items': ['TextColor', 'BGColor']},
            {'name': 'paragraph', 'items': ['NumberedList', 'BulletedList', '-', 'Outdent', 'Indent', '-', 'Blockquote', '-',
                                            'JustifyLeft', 'JustifyCenter', 'JustifyRight', 'JustifyBlock']},
            {'name': 'links', 'items': ['Link', 'Unlink', 'Anchor']},
            {'name': 'insert', 'items': ['Image', 'Table', 'HorizontalRule', 'SpecialChar', 'CodeSnippet']},
            {'name': 'tools', 'items': ['Maximize', 'Source']},
        ],
        'extraPlugins': ','.join(['uploadimage', 'image2', 'codesnippet', 'widget', 'lineutils']),
        'codeSnippet_theme': 'monokai_sublime',
        'height': 520,
        'width': '100%',
        'tabSpaces': 4,
        # Keep semantic, SEO-friendly markup (don't strip ids/classes used for tables/anchors).
        'allowedContent': True,
        'removeButtons': '',
        'format_tags': 'p;h2;h3;h4;pre',
    },
}


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'rocketops_core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'rocketops_core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

CORS_ALLOW_ALL_ORIGINS = True # For development, we allow all. Change in production.

# ── AI Command Center (OpenAI) ────────────────────────────────────────────────
# Key is read from the environment / .env only — never committed.
OPENAI_API_KEY = os.environ.get('OPENAI_API_KEY', '')
# Reasoning brain + cheap/fast model. Override per-account via .env if needed.
OPENAI_COMMAND_MODEL = os.environ.get('OPENAI_COMMAND_MODEL', 'gpt-4o')
OPENAI_FAST_MODEL = os.environ.get('OPENAI_FAST_MODEL', 'gpt-4o-mini')

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

STATIC_ROOT = BASE_DIR / 'staticfiles'

JAZZMIN_SETTINGS = {
    # ── Branding ────────────────────────────────────────────────────────────
    "site_title": "RocketOps Admin",
    "site_header": "RocketOps",
    "site_brand": "RocketOps",
    "site_logo": "admin/logo.png",        # shown in the sidebar header
    "login_logo": "admin/logo.png",       # shown on the login page
    "site_icon": "admin/logo.png",        # browser tab favicon
    "welcome_sign": "Welcome back to RocketOps",
    "copyright": "© 2025 RocketOps AI — All rights reserved",

    # ── Search ───────────────────────────────────────────────────────────────
    "search_model": ["api.TeamMember", "api.Service", "api.ContactSubmission", "api.Blog", "crm.Contact", "crm.Deal", "crm.Company"],
    "user_avatar": None,

    # ── Top Navigation ───────────────────────────────────────────────────────
    "topmenu_links": [
        {"name": "Dashboard", "url": "admin:index", "permissions": ["auth.view_user"]},
        {"name": "📬 Inbox", "model": "api.ContactSubmission"},
        {"name": "✍️ Blog", "model": "api.Blog"},
        {"name": "🎯 CRM", "url": "http://localhost:3000/crm", "new_window": True},
        {"name": "🌐 View Site", "url": "http://localhost:3000", "new_window": True},
    ],

    # ── Sidebar ──────────────────────────────────────────────────────────────
    "show_sidebar": True,
    "navigation_expanded": True,
    "hide_apps": [],
    "hide_models": [],
    "order_with_respect_to": [
        "api",
        "api.ContactSubmission",
        "api.Blog",
        "api.BlogCategory",
        "api.TeamMember",
        "api.Service",
        "api.Product",
        "auth",
    ],

    # ── Icons ────────────────────────────────────────────────────────────────
    "icons": {
        "auth":                   "fas fa-shield-alt",
        "auth.user":              "fas fa-user-circle",
        "auth.Group":             "fas fa-layer-group",
        "api":                    "fas fa-rocket",
        "api.TeamMember":         "fas fa-users",
        "api.Service":            "fas fa-cogs",
        "api.ServiceFeature":     "fas fa-puzzle-piece",
        "api.Product":            "fas fa-box-open",
        "api.ContactSubmission":  "fas fa-envelope-open-text",
        "api.CompanyCategory":    "fas fa-tags",
        "api.CompanyLogo":        "fas fa-images",
        "api.AIProvider":         "fas fa-microchip",
        "api.Testimonial":        "fas fa-quote-left",
        "api.Faq":                "fas fa-question-circle",
        "api.CaseStudy":          "fas fa-briefcase",
        "api.Blog":               "fas fa-feather-alt",
        "api.BlogCategory":       "fas fa-folder-open",
        "api.BlogFAQ":            "fas fa-comments",
        "authtoken":              "fas fa-key",
        "authtoken.TokenProxy":   "fas fa-key",
        "crm":                    "fas fa-bullseye",
        "crm.Company":            "fas fa-building",
        "crm.Contact":            "fas fa-address-card",
        "crm.Deal":               "fas fa-handshake",
        "crm.Activity":           "fas fa-stream",
        "crm.PipelineStage":      "fas fa-columns",
        "crm.AIActionLog":        "fas fa-clipboard-list",
    },
    "default_icon_parents":  "fas fa-chevron-right",
    "default_icon_children": "fas fa-dot-circle",

    # ── UI ───────────────────────────────────────────────────────────────────
    "related_modal_active": True,
    "custom_css": "admin/css/custom_admin.css",
    "custom_js": None,
    "use_google_fonts_cdn": True,
    "show_ui_builder": False,
    "changeform_format": "horizontal_tabs",
    "changeform_format_overrides": {
        "auth.user": "collapsible",
        "auth.group": "vertical_tabs",
        # CKEditor + inlines are unreliable inside jazzmin 3.0.4 horizontal_tabs
        # (the tab toggles don't render, so tabs can't switch and inlines past the
        # first tab are unreachable). Render these as a single scrolling form so the
        # rich-text editor and the per-blog FAQ inline always work.
        "api.blog": "single",
        "api.blogcategory": "single",
    },
}

JAZZMIN_UI_TWEAKS = {
    "navbar_small_text": False,
    "footer_small_text": True,
    "body_small_text": False,
    "brand_small_text": False,
    "brand_colour": "navbar-dark",
    "accent": "accent-primary",
    "navbar": "navbar-dark",
    "no_navbar_border": True,
    "navbar_fixed": True,
    "layout_boxed": False,
    "footer_fixed": False,
    "sidebar_fixed": True,
    "sidebar": "sidebar-dark-primary",
    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": True,
    "sidebar_nav_compact_style": False,
    "sidebar_nav_legacy_style": False,
    "sidebar_nav_flat_style": False,
    "theme": "darkly",
    "dark_mode_theme": "darkly",
    "button_classes": {
        "primary":   "btn-primary",
        "secondary": "btn-secondary",
        "info":      "btn-info",
        "warning":   "btn-warning",
        "danger":    "btn-danger",
        "success":   "btn-success",
    },
}

STATICFILES_DIRS = [BASE_DIR / 'static']
